name: Docker Image Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: DockerHub login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Build the Docker image
      run: |
        docker buildx build --dockerfile Dockerfile --platform linux/amd64,linux/arm64 -t jmshum/amazonlinux-cli-tools --push . 
